name: VK to GitHub Sync

on:
  schedule:
    # Запуск каждый час
    - cron: '0 * * * *'
  workflow_dispatch:  # Ручной запуск
  push:
    branches: [ main ]

jobs:
  sync-vk-to-gh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        
    - name: Run VK Sync
      env:
        VK_ACCESS_TOKEN: ${{ secrets.VK_ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VK_GROUP_ID: ${{ secrets.VK_GROUP_ID }}
      run: |
        echo "Starting VK sync..."
        node scripts/vk-sync.js
        
        if [ $? -eq 0 ]; then
          echo "✅ Sync completed successfully"
        else
          echo "❌ Sync failed"
          exit 1
        fi
        
    - name: Commit and push if changed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add assets/data/next-meeting.json
        
        # Проверяем есть ли изменения
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update: Sync next meeting from VK [skip ci]"
          git push
          echo "Changes committed and pushed"
        fi